language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
env:
  global:
    secure: iGqqCBHTDmD6UHroFbuBUB9sGWsvymHBO46XBSdFn1nro4XiAOGBjqHJf2AiPTPAoTJ4ZCIp6e0IhS9RB1mIE3B6UCEbkzWYz7HC0cl54ADTLVj6Scs9l0TW1tUjCuDMs2TqkA+9v/pi1/dG1qJdfh7MaT60Fcb+35Ahx/UsYtJQAeN3cov7i9DNthgdeb3LWITkF9jrOTiliCjHrovsq/ajE75mxk1zYFljZ9mIcySv83NIdUWR74MKSBLSFc7tzT/c5tEQk7ocerJ1FyoKGXnAk/3SlNVguGQYORNoYHyzaz3ibPM4t8vW+gtNF23jKQfSKnq4/a4iYGlHow08OlyMNXcY2FRoiJaMaabNHaOEr653cmnFGbLuirsv7GOTnipZt7CHY7Pi+nIe9Xcil8dBanZTXMqAWxsLJEBKy8F46GHiMYJHn4EKP2uoiNPK1g1lueoI0VoqQNsBCdnr7YDBRqcoEcTTYqKrwdPfsP+6OJ76pyDb9nBQPBCHOTHxIJU26OZXi29qVm2KfvpBX1dDNaZ1UroPXyTl7dXk6IOog3MCjXs5YZ7ojSWqy8Snt6pc13nq0YF4fvhLxK2dQOvyl0m7hdNIbegdGtmoxPYySqu9QuiANCAJurL31rl9HoCirY137MdInrX/3zGGGpWf8wlTm/rVKVC7TcFrc5o=
